
Du must dir 


@startuml qovaArchitecture 

package Course{

    class Course{

        - String name
        - int Semester
        - Type type
        - bytes QRCode
        - String optQuestion1
        - String optQuestion2
        - String optQuestion3

==

        'Constructor'
        + Course(String name, int Semester, Type type, QRCode qrCode, String optQuestion1, String optQuestion2, String optQuestion3)
        + Getter()       'for all attributes' 
        + Setter()       'for all attributes' 
        + getId()

    }

    class CourseController{
       
        - final CourseManagement courseManagement

==

        + CourseController(CourseManagement courseManagement) 
        + String courseDetails(Model model, Long id)
            'GetMapping method'
        + String createCourse(Model model, CourseForm form)         
            'PostMapping method to verify user input'                            
        + String createCourseValidation(Model model, CourseForm form, BindingResult result)
            'GetMapping method'
        + String editCourse(Model model, CourseForm form, Long id)
            'PostMapping method to validate user input'
        + String editCourseValidation(Model model, CourseForm form, Long id, BindingResult result)


    }

    class CourseManagement{

    }

    class CourseForm{
        
        - String name
        - int Semester
        - Type type
        - bytes QRCode
        - String optQuestion1
        - String optQuestion2
        - String optQuestion3

==
        + String getName()
        + int getSemester()
        + Type getType()
        + bytes getQRCode()
        + String getOptQues1()
        + String getOptQues2()
        + String getOptQues3()

    }

    enum Type {
        LECTURE
        TUTORIAL
        SEMINAR
    }


    'Relations'
    Type --* Course


}

package Users{
    class User{

    }

    class UserController{

    }

    class UserManagement{

    }

    class UserForm{

    }

    class UserRepository{

    }
}

@enduml