package qova.enums;

public enum CourseFaculty {
    BIOLOGY, 
    CHEMISTRY,
    FOOD_CHEMISTRY, 
    MATHEMATICS, 
    PHYSICS,
    PSYCHOLOGY,
    ARTS_HUMANITIES_SOCIAL_SCIENCE,
    EDUCATION,
    LAW,
    LINGUISTICS,
    LITERATURE,
    CULTURAL_STUDIES,
    ELECTRICAL_AND_COMPUTER_ENGINEERING,
    COMPUTER_SCIENCE,
    MECHANICAL_SCIENCE_AND_ENGINEERING,
    ARCHITECTURE,
    CIVIL_ENGINEERING,
    ENVIRONMENTAL_SCIENCES,
    TRANSPORTATION_AND_TRAFFIC_SCIENCE,
    BUSSINESS_AND_ECONOMICS,
    MEDICINE;

}